### ISSUE TITLE
Missing in Instructions: Install Node and NPM dependencies

### ISSUE THREAD

**Issue by jaller94** [BenediktMagnus/OpenRCT2TwitchServer#2]
In the README steps are missing to install the NPM and the projects dependencies before running the Node script.

To serve a wider audience the instructions should not imply that you know about Node and how its package system works.

Please add the following steps:
1. Install [Node.js](https://nodejs.org/) either from their website or through the software distribution in your operating system. The following steps imply that node is a globally accessible command. If this is not the case, you may run it from any folder by specifying the path of your installation like /path/to/node.
2. To install the projects dependencies run `npm ci`. The program npm can be found in the folder of you Node.JS installation.

**Comment by BenediktMagnus** [comment]
This has been added.
Thank you for your help!
