### ISSUE TITLE
Please specify the version of the tmi.js depencency

### ISSUE THREAD

**Issue by jaller94** [BenediktMagnus/OpenRCT2TwitchServer#3]
https://github.com/BenediktMagnus/OpenRCT2TwitchServer/blob/3aed001b50e242fdd51dc3ef42038be87b207dc5/package.json#L8

When not specifying the version of a dependency, `npm audit` will fail:
```
$ npm audit
npm ERR! code E400
npm ERR! 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits
```

As of 2018-Dec-31, the latest version of tmi.js is 1.2.1, which is also the version locked in `package-lock.json`.

**Comment by BenediktMagnus** [comment]
I have set the version for tmi.js.
Thank you for mentioning this!
