### ISSUE TITLE
Potential security issues in dependencies of tmi.js

### ISSUE THREAD

**Issue by jaller94** [BenediktMagnus/OpenRCT2TwitchServer#4]
The project tmi.js is known to have several security issues according to the NPM Security advisory. I have not taken the time to identify, if these are affecting the uses in OpenRCT2TwitchServer.

Ticket in the upstream repo: tmijs/tmi.js#311

To check your dependencies for vulnerabilities run `npm audit`. If they have been fixed in their upstream packages, you can resolve them by running `npm audit fix`. In this case, the issues have not been resolved in tmi.js.

**Comment by BenediktMagnus** [comment]
By updating the dependencies (more correct: Updating the package-lock while solving #3) all potential security issues were solved.
Thank you for bringing this to attention!
