### ISSUE TITLE
Missing in Instructions: "Enable Twitch integration"

### ISSUE THREAD

**Issue by jaller94** [BenediktMagnus/OpenRCT2TwitchServer#6]
When playing a campaign, one needs to check "Enable Twitch integration" in the save dropdown menu of the game for the world to be affected.

This step can easily be missed when starting with OpenRCT streaming. It should be explained or an article from OpenRCT about this should be referenced in the instructions.

**Comment by BenediktMagnus** [comment]
This has been added.
Thank you!
